name: ceiba_users
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.14
  go_router: ^14.4.1
  http: ^1.2.2
  infinite_scroll_pagination: ^4.1.0
  package_info_plus: ^8.1.1
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

